# Vox AI Chatbot - Development Roadmap
# This file defines the GitHub Projects structure for the roadmap

name: "Vox AI Chatbot Roadmap"
description: "Development roadmap and feature tracking for Vox AI Chatbot"

# Project Views
views:
  - name: "📋 Backlog"
    description: "All planned features and improvements"
    filter: "label:backlog"
    
  - name: "🚀 In Progress"
    description: "Currently being worked on"
    filter: "label:in-progress"
    
  - name: "🧪 Testing"
    description: "Features ready for testing"
    filter: "label:testing"
    
  - name: "✅ Completed"
    description: "Completed features and fixes"
    filter: "label:completed"

# Project Milestones
milestones:
  - title: "Phase 1: Foundation & Stability"
    description: "Stabilize core functionality and improve user experience"
    due_date: "2024-03-31"
    
  - title: "Phase 2: Enhanced Features"
    description: "Add advanced communication features and user management"
    due_date: "2024-06-30"
    
  - title: "Phase 3: AI & Intelligence"
    description: "Expand AI capabilities and add multiple providers"
    due_date: "2024-09-30"
    
  - title: "Phase 4: Mobile & Accessibility"
    description: "Expand to mobile platforms and improve accessibility"
    due_date: "2024-12-31"
    
  - title: "Phase 5: Monetization & Web3"
    description: "Implement monetization and Web3 features"
    due_date: "2025-03-31"

# Labels for categorization
labels:
  - name: "priority:high"
    color: "d73a4a"
    description: "High priority items"
    
  - name: "priority:medium"
    color: "f9d0c4"
    description: "Medium priority items"
    
  - name: "priority:low"
    color: "0e8a16"
    description: "Low priority items"
    
  - name: "effort:small"
    color: "7057ff"
    description: "Small effort required"
    
  - name: "effort:medium"
    color: "fbca04"
    description: "Medium effort required"
    
  - name: "effort:large"
    color: "d93f0b"
    description: "Large effort required"
    
  - name: "platform:discord"
    color: "5865f2"
    description: "Discord bot related"
    
  - name: "platform:telegram"
    color: "0088cc"
    description: "Telegram bot related"
    
  - name: "platform:whatsapp"
    color: "25d366"
    description: "WhatsApp bot related"
    
  - name: "platform:web"
    color: "ff6b6b"
    description: "Web frontend related"
    
  - name: "platform:mobile"
    color: "4ecdc4"
    description: "Mobile app related"
    
  - name: "type:feature"
    color: "a2eeef"
    description: "New feature"
    
  - name: "type:bug"
    color: "d73a4a"
    description: "Bug fix"
    
  - name: "type:enhancement"
    color: "a2eeef"
    description: "Enhancement"
    
  - name: "type:documentation"
    color: "0075ca"
    description: "Documentation"
    
  - name: "type:refactor"
    color: "7057ff"
    description: "Code refactoring"
    
  - name: "status:backlog"
    color: "c5def5"
    description: "In backlog"
    
  - name: "status:in-progress"
    color: "fbca04"
    description: "In progress"
    
  - name: "status:testing"
    color: "f9d0c4"
    description: "Ready for testing"
    
  - name: "status:completed"
    color: "0e8a16"
    description: "Completed"
    
  - name: "status:blocked"
    color: "d73a4a"
    description: "Blocked"
    
  - name: "area:ai"
    color: "ff6b6b"
    description: "AI and machine learning"
    
  - name: "area:ui"
    color: "4ecdc4"
    description: "User interface"
    
  - name: "area:backend"
    color: "7057ff"
    description: "Backend development"
    
  - name: "area:frontend"
    color: "a2eeef"
    description: "Frontend development"
    
  - name: "area:web3"
    color: "f9d0c4"
    description: "Web3 integration"
    
  - name: "area:mobile"
    color: "0e8a16"
    description: "Mobile development"
